FROM node:20-bullseye

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y python3 make g++ git && rm -rf /var/lib/apt/lists/*

COPY app/package.json package.json
COPY app/package-lock.json package-lock.json
RUN npm ci

COPY app/. .

ENV NODE_ENV=production
EXPOSE 3000

RUN make build

CMD ["make", "start"]